# Generated by Django 4.0.3 on 2022-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(max_length=22)),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
