# Generated by Django 3.1.4 on 2022-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220413_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
