# Generated by Django 4.0.3 on 2022-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_sellers_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soft_product',
            field=models.BooleanField(default=False),
        ),
    ]
