# Generated by Django 4.0.3 on 2022-03-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='soft_product',
            new_name='is_active',
        ),
    ]
