# Generated by Django 3.1.4 on 2022-04-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220415_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
