# Generated by Django 4.0.3 on 2022-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_soft_product_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellers',
            old_name='Shop_name',
            new_name='shop_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
