# Generated by Django 4.0.3 on 2022-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_category_category_name_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
